# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: mvn verify

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17, 21]
        include:
          - { os: ubuntu-latest, verifyFormatOpt: '-Drevelc.verifyFormat' }
          - { os: macos-latest, verifyFormatOpt: '-Drevelc.verifyFormat' }
          - { os: windows-latest, verifyFormatOpt: '-Drevelc.skipFormat' }
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: 'maven'
    - name: Download Maven Wrapper
      run: mvn wrapper:wrapper "-Dmaven=3.9.8"
    - name: Build with Maven
      run: ./mvnw -B -V -e "-Dstyle.color=always" verify "-Drevelc.skipFormat" "${{ matrix.verifyFormatOpt }}"
      env:
        MAVEN_OPTS: -Djansi.force=true
    - name: View IT build log on failure
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: apilyzer-reports-java-${{ matrix.java }}-os-${{ matrix.os }}
        path: |
          target/its/**/apilyzer.txt
          target/its/**/build.log
        if-no-files-found: ignore

